repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint

  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.1
    hooks:
      - id: action-validator
