# config.yaml
detectors:
- name: Aliyun Secret
  keywords:
  - AccessKey
  regex:
    adjective: ([A|a]ccess[K|k]ey[S|s]ecret)
- name: 内网IP
  keywords:
    - "10."
    - "172."
    - "192.1"
    - "169."
  regex:
    adjective: ((127\.0\.0\.1)|(10\.\d{1,3}\.\d{1,3}\.\d{1,3})|(172\.((1[6-9])|(2\d)|(3[01]))\.\d{1,3}\.\d{1,3})|(192\.168\.\d{1,3}\.\d{1,3}))
